import { FilterOperators } from "../../../models/filters/filterOperators.enum";
import { ColumnHeader } from "../../../models/dataGrid/columnHeader.model";

export const columns: ColumnHeader[] = [
  {
    name: "Id",
    propertyName: "id",
    operators: [
      FilterOperators.Contains,
      FilterOperators.DoesNotContain,
      FilterOperators.Equals,
      FilterOperators.DoesNotEqual,
      FilterOperators.StartsWith,
      FilterOperators.EndsWith,
      FilterOperators.OneOf,
      FilterOperators.NotOneOf,
      FilterOperators.MinimumLength,
      FilterOperators.MaxiumumLength,
    ],
    activeFilters: [],
    sort: { sorted: false, direction: null },
  },
  {
    name: "State",
    propertyName: "state",
    operators: [
      FilterOperators.Contains,
      FilterOperators.DoesNotContain,
      FilterOperators.Equals,
      FilterOperators.DoesNotEqual,
      FilterOperators.StartsWith,
      FilterOperators.EndsWith,
      FilterOperators.OneOf,
      FilterOperators.NotOneOf,
      FilterOperators.MinimumLength,
      FilterOperators.MaxiumumLength,
    ],
    activeFilters: [],
    sort: { sorted: false, direction: null },
  },
  {
    name: "User",
    propertyName: "user",
    operators: [
      FilterOperators.Contains,
      FilterOperators.DoesNotContain,
      FilterOperators.Equals,
      FilterOperators.DoesNotEqual,
      FilterOperators.StartsWith,
      FilterOperators.EndsWith,
      FilterOperators.OneOf,
      FilterOperators.NotOneOf,
      FilterOperators.MinimumLength,
      FilterOperators.MaxiumumLength,
    ],
    activeFilters: [],
    sort: { sorted: false, direction: null },
  },
  {
    name: "Logical Start",
    propertyName: "logical_start",
    operators: [
      FilterOperators.GreaterThan,
      FilterOperators.GreaterThanOrEqual,
      FilterOperators.LessThan,
      FilterOperators.LessThanOrEqual,
      FilterOperators.Equals,
      FilterOperators.DoesNotEqual,
      FilterOperators.OneOf,
      FilterOperators.NotOneOf,
    ],
    activeFilters: [],
    sort: { sorted: false, direction: null },
  },
  {
    name: "Logical End",
    propertyName: "logical_end",
    operators: [
      FilterOperators.GreaterThan,
      FilterOperators.GreaterThanOrEqual,
      FilterOperators.LessThan,
      FilterOperators.LessThanOrEqual,
      FilterOperators.Equals,
      FilterOperators.DoesNotEqual,
      FilterOperators.OneOf,
      FilterOperators.NotOneOf,
    ],
    activeFilters: [],
    sort: { sorted: false, direction: null },
  },
  {
    name: "Run Start",
    propertyName: "run_start",
    operators: [
      FilterOperators.GreaterThan,
      FilterOperators.GreaterThanOrEqual,
      FilterOperators.LessThan,
      FilterOperators.LessThanOrEqual,
      FilterOperators.Equals,
      FilterOperators.DoesNotEqual,
      FilterOperators.OneOf,
      FilterOperators.NotOneOf,
    ],
    activeFilters: [],
    sort: { sorted: false, direction: null },
  },
  {
    name: "Run End",
    propertyName: "run_end",
    operators: [
      FilterOperators.GreaterThan,
      FilterOperators.GreaterThanOrEqual,
      FilterOperators.LessThan,
      FilterOperators.LessThanOrEqual,
      FilterOperators.Equals,
      FilterOperators.DoesNotEqual,
      FilterOperators.OneOf,
      FilterOperators.NotOneOf,
    ],
    activeFilters: [],
    sort: { sorted: false, direction: null },
  },
] as const;
